redmine_db_database: defaultdb
redmine_db_username: doadmin
redmine_db_port: 25060
datadog_site: datadoghq.eu
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: "Check availability of the first web application"
        url: "http://164.90.188.112"
      - name: "Check availability of the second web application"
        url: "http://165.232.122.151"
